### ISSUE TITLE
Does the DTLS connection look like HTTPS to DPI?

### ISSUE THREAD

**Issue by simpz** [SenseUnit/dtlspipe#21]
This is a very cool looking project that finally allows UDP over an stunnel like session without jumping through lots of hoops. It's deserves much more recognition.

One thing that stunnel does do is it makes (I believe) the session hard to distinguish from HTTPS, so hard for any
Deep Packet Inspection system to block (without blocking all HTTPS). 

Does dtlspipe look similar to HTTPS or stunnel, so will be similarly hard to block?

Thanks again

**Comment by Snawoot** [comment]
Hi!

No, HTTPS is based on TCP which is connection-oriented protocol. DTLS uses UDP as underlying protocol. DTLS is chosen for that purpose because it is also used by WebRTC, which is sometimes used by web-browsers for real-time communications like video- or audiocalls. Snowflake bridges of Tor also use similar approach, but in their case such bridges are often crawled by state actors and banned.

stunnel is a great tool, but piping UDP through any kind of TCP connection performs really bad[^1][^2], and if we want to carry some VPN datagrams like Wireguard protocol, we would want something UDP-based. For this reason, for carrying UDP, DTLS is fine.

Regarding resilience against censorship such protocol is plausible-looking, but use of it at scale or prolonged sessions sometimes get banned by Chinese GFW. In this case port hopping or address hopping[^3] might help.

[^1]: https://blog.vpntracker.com/why-vpn-tunneling-over-tcp-sucks/
[^2]: https://openvpn.net/faq/what-is-tcp-meltdown/
[^3]: See `hoppingclient` subcommand of `dtlspipe`. On server side configuration should be done in such way that different ports or addresses get `DNAT`-ed to dtlspipe server port, pretty much [like for hysteria server](https://v1.hysteria.network/docs/port-hopping/).
